services:
  bank2tax:
    image: stefanwaterval/bank2tax:latest
    ports:
      - "8080:8080"
    environment:
      OLLAMA_BASE_URL: http://host.docker.internal:11434
      OLLAMA_MODEL: llama3.1:8b
      OLLAMA_TEMPERATURE: "0.0"
      OLLAMA_TIMEOUT_S: "120"