[project]
name = "bank2tax"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "docling>=2.74.0",
    "nicegui>=3.7.1",
    "pydantic-ai-slim>=1.62.0",
]
